services:
  postgres:
    image: postgres:18
    container_name: 3p-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: orcamentos
      POSTGRES_USER: orcamentos
      POSTGRES_PASSWORD: orcamentos_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: