-- ============================================================
-- Sistema de Orçamentos 3P
-- Schema inicial - PostgreSQL
-- ============================================================

BEGIN;

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE status_registro AS ENUM (
    'ATIVO',
    'INATIVO'
);

CREATE TYPE status_associacao AS ENUM (
    'EXATO',
    'SEMASSOCIACAO'
);

CREATE TYPE motivo_material AS ENUM (
    'MATCH_EXATO_ATIVO',
    'CANDIDATO_TECNICO_UNICO',
    'CANDIDATOS_AMBIGUOS',
    'SEM_CANDIDATO_COMPATIVEL'
);

CREATE TYPE fonte_neoenergia AS ENUM (
    'NEOENERGIA_REDE',
    'NEOENERGIA_SUBESTACOES'
);

CREATE TYPE status_carrinho AS ENUM (
    'RASCUNHO',
    'CALCULADO',
    'APROVADO',
    'CANCELADO'
);

-- ============================================================
-- CLIENTES
-- ============================================================

CREATE TABLE cliente (
                         id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome            VARCHAR(255) NOT NULL,
                         documento       VARCHAR(50),
                         status          status_registro NOT NULL DEFAULT 'ATIVO',

                         created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cliente_nome
    ON cliente (nome);

-- ============================================================
-- FORNECEDORES
-- ============================================================

CREATE TABLE fornecedor (
                            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            razao_social    VARCHAR(255) NOT NULL,
                            nome_fantasia   VARCHAR(255),
                            cnpj            VARCHAR(30),
                            email           VARCHAR(255),
                            telefone        VARCHAR(50),
                            status          status_registro NOT NULL DEFAULT 'ATIVO',

                            created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fornecedor_razao_social
    ON fornecedor (razao_social);

CREATE INDEX idx_fornecedor_cnpj
    ON fornecedor (cnpj);

-- ============================================================
-- ORÇAMENTOS
-- ============================================================

CREATE TABLE orcamento (
                           id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           numero_orcamento    VARCHAR(100),
                           cliente_id          INTEGER,
                           fornecedor_origem_id INTEGER,
                           data_orcamento      TIMESTAMPTZ,

                           subtotal            NUMERIC(18, 2),
                           frete               NUMERIC(18, 2),
                           desconto            NUMERIC(18, 2),
                           tributos            NUMERIC(18, 2),
                           valor_total         NUMERIC(18, 2),

                           status              VARCHAR(50),
                           arquivo_origem      TEXT,
                           drive_file_id       VARCHAR(255),

                           created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_orcamento_cliente
                               FOREIGN KEY (cliente_id)
                                   REFERENCES cliente(id),

                           CONSTRAINT fk_orcamento_fornecedor
                               FOREIGN KEY (fornecedor_origem_id)
                                   REFERENCES fornecedor(id)
);

CREATE INDEX idx_orcamento_numero
    ON orcamento (numero_orcamento);

CREATE INDEX idx_orcamento_cliente
    ON orcamento (cliente_id);

CREATE INDEX idx_orcamento_fornecedor
    ON orcamento (fornecedor_origem_id);

-- ============================================================
-- MATERIAIS OFICIAIS
-- ============================================================

CREATE TABLE material_oficial (
                                  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nome                    VARCHAR(500) NOT NULL,
                                  nome_normalizado        VARCHAR(500) NOT NULL,
                                  categoria               VARCHAR(255),
                                  especificacao_tecnica   TEXT,
                                  status                  status_registro NOT NULL DEFAULT 'ATIVO',

                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_material_oficial_nome_normalizado
    ON material_oficial (nome_normalizado);

CREATE INDEX idx_material_oficial_categoria
    ON material_oficial (categoria);

-- ============================================================
-- ITENS DE ORÇAMENTO
-- ============================================================

CREATE TABLE item_orcamento (
                                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                orcamento_id                INTEGER NOT NULL,
                                numero_item                 INTEGER,
                                codigo_item                 VARCHAR(255),

                                descricao_original          TEXT NOT NULL,
                                descricao_normalizada       TEXT,

                                quantidade                  NUMERIC(18, 4),
                                unidade                     VARCHAR(50),
                                preco_unitario              NUMERIC(18, 4),
                                preco_total                 NUMERIC(18, 4),

                                material_oficial_id         INTEGER,

                                status_associacao           status_associacao NOT NULL DEFAULT 'SEMASSOCIACAO',
                                motivo_material             motivo_material,
                                match_automatico            BOOLEAN NOT NULL DEFAULT FALSE,
                                revisao_humana_obrigatoria  BOOLEAN NOT NULL DEFAULT TRUE,

                                observacao                  TEXT,

                                created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_item_orcamento_orcamento
                                    FOREIGN KEY (orcamento_id)
                                        REFERENCES orcamento(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_item_orcamento_material
                                    FOREIGN KEY (material_oficial_id)
                                        REFERENCES material_oficial(id)
);

CREATE INDEX idx_item_orcamento_orcamento
    ON item_orcamento (orcamento_id);

CREATE INDEX idx_item_orcamento_codigo
    ON item_orcamento (codigo_item);

CREATE INDEX idx_item_orcamento_material
    ON item_orcamento (material_oficial_id);

-- ============================================================
-- CATÁLOGO NEOENERGIA
-- ============================================================

CREATE TABLE material_neoenergia (
                                     id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     material_oficial_id     INTEGER,

                                     codigo_nordeste         VARCHAR(255),
                                     codigo_elektro          VARCHAR(255),
                                     codigo_brasilia         VARCHAR(255),

                                     descricao               TEXT NOT NULL,
                                     descricao_completa      TEXT,
                                     especificacao_tecnica   TEXT,
                                     familia                 VARCHAR(255),
                                     subfamilia              VARCHAR(255),

                                     fonte                   fonte_neoenergia NOT NULL,
                                     chave_importacao        TEXT NOT NULL UNIQUE,

                                     created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_material_neoenergia_material
                                         FOREIGN KEY (material_oficial_id)
                                             REFERENCES material_oficial(id)
);

CREATE INDEX idx_material_neoenergia_material
    ON material_neoenergia (material_oficial_id);

CREATE INDEX idx_material_neoenergia_fonte
    ON material_neoenergia (fonte);

CREATE INDEX idx_material_neoenergia_codigo_nordeste
    ON material_neoenergia (codigo_nordeste);

-- ============================================================
-- MATERIAL × FORNECEDOR HOMOLOGADO
-- ============================================================

CREATE TABLE material_fornecedor_homologado (
                                                id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                material_neoenergia_id      INTEGER NOT NULL,
                                                fornecedor_id               INTEGER NOT NULL,

                                                referencia_fornecedor       VARCHAR(255),
                                                desenho_fornecedor          VARCHAR(255),

                                                data_homologacao            TIMESTAMPTZ,
                                                data_vencimento_homologacao TIMESTAMPTZ,

                                                documentacao                TEXT,
                                                modo_fornecimento           VARCHAR(255),
                                                ca                          VARCHAR(255),
                                                tipo_gestao_recebimento     VARCHAR(255),

                                                status_homologacao          VARCHAR(100),
                                                observacao                  TEXT,

                                                created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                                CONSTRAINT fk_mfh_material
                                                    FOREIGN KEY (material_neoenergia_id)
                                                        REFERENCES material_neoenergia(id)
                                                        ON DELETE CASCADE,

                                                CONSTRAINT fk_mfh_fornecedor
                                                    FOREIGN KEY (fornecedor_id)
                                                        REFERENCES fornecedor(id),

                                                CONSTRAINT uq_mfh_material_fornecedor
                                                    UNIQUE (material_neoenergia_id, fornecedor_id)
);

CREATE INDEX idx_mfh_material
    ON material_fornecedor_homologado (material_neoenergia_id);

CREATE INDEX idx_mfh_fornecedor
    ON material_fornecedor_homologado (fornecedor_id);

-- ============================================================
-- COTAÇÕES
-- ============================================================

CREATE TABLE cotacao (
                         id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         fornecedor_id       INTEGER NOT NULL,

                         numero_cotacao      VARCHAR(100),
                         data_cotacao        TIMESTAMPTZ,
                         validade            TIMESTAMPTZ,

                         frete               NUMERIC(18, 2),
                         desconto            NUMERIC(18, 2),
                         condicao_pagamento  VARCHAR(255),
                         prazo_entrega       VARCHAR(255),
                         valor_total         NUMERIC(18, 2),

                         arquivo_origem      TEXT,

                         created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_cotacao_fornecedor
                             FOREIGN KEY (fornecedor_id)
                                 REFERENCES fornecedor(id)
);

CREATE INDEX idx_cotacao_fornecedor
    ON cotacao (fornecedor_id);

CREATE INDEX idx_cotacao_numero
    ON cotacao (numero_cotacao);

-- ============================================================
-- OFERTAS DE ITENS
-- ============================================================

CREATE TABLE oferta_item (
                             id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             cotacao_id              INTEGER NOT NULL,
                             fornecedor_id           INTEGER NOT NULL,
                             material_oficial_id     INTEGER,

                             descricao_fornecedor    TEXT NOT NULL,

                             quantidade              NUMERIC(18, 4),
                             unidade                 VARCHAR(50),
                             preco_unitario          NUMERIC(18, 4),
                             preco_total             NUMERIC(18, 4),

                             prazo_entrega           VARCHAR(255),
                             valida                  BOOLEAN NOT NULL DEFAULT TRUE,

                             created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_oferta_cotacao
                                 FOREIGN KEY (cotacao_id)
                                     REFERENCES cotacao(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_oferta_fornecedor
                                 FOREIGN KEY (fornecedor_id)
                                     REFERENCES fornecedor(id),

                             CONSTRAINT fk_oferta_material
                                 FOREIGN KEY (material_oficial_id)
                                     REFERENCES material_oficial(id)
);

CREATE INDEX idx_oferta_cotacao
    ON oferta_item (cotacao_id);

CREATE INDEX idx_oferta_fornecedor
    ON oferta_item (fornecedor_id);

CREATE INDEX idx_oferta_material
    ON oferta_item (material_oficial_id);

CREATE INDEX idx_oferta_valida
    ON oferta_item (valida);

-- ============================================================
-- CARRINHO OTIMIZADO
-- ============================================================

CREATE TABLE carrinho (
                          id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          orcamento_id        INTEGER NOT NULL,

                          status              status_carrinho NOT NULL DEFAULT 'RASCUNHO',

                          valor_base          NUMERIC(18, 2),
                          valor_otimizado     NUMERIC(18, 2),
                          economia            NUMERIC(18, 2),

                          created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_carrinho_orcamento
                              FOREIGN KEY (orcamento_id)
                                  REFERENCES orcamento(id)
);

CREATE INDEX idx_carrinho_orcamento
    ON carrinho (orcamento_id);

-- ============================================================
-- ITENS DO CARRINHO
-- ============================================================

CREATE TABLE carrinho_item (
                               id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               carrinho_id                     INTEGER NOT NULL,
                               item_orcamento_id               INTEGER NOT NULL,

                               oferta_item_id                  INTEGER,
                               fornecedor_id                   INTEGER,

                               quantidade                      NUMERIC(18, 4),
                               preco_unitario                  NUMERIC(18, 4),
                               preco_total                     NUMERIC(18, 4),

                               selecionado_automaticamente     BOOLEAN NOT NULL DEFAULT FALSE,
                               selecionado_usuario             BOOLEAN NOT NULL DEFAULT FALSE,

                               created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_carrinho_item_carrinho
                                   FOREIGN KEY (carrinho_id)
                                       REFERENCES carrinho(id)
                                       ON DELETE CASCADE,

                               CONSTRAINT fk_carrinho_item_orcamento
                                   FOREIGN KEY (item_orcamento_id)
                                       REFERENCES item_orcamento(id),

                               CONSTRAINT fk_carrinho_item_oferta
                                   FOREIGN KEY (oferta_item_id)
                                       REFERENCES oferta_item(id),

                               CONSTRAINT fk_carrinho_item_fornecedor
                                   FOREIGN KEY (fornecedor_id)
                                       REFERENCES fornecedor(id)
);

CREATE INDEX idx_carrinho_item_carrinho
    ON carrinho_item (carrinho_id);

CREATE INDEX idx_carrinho_item_orcamento
    ON carrinho_item (item_orcamento_id);

CREATE INDEX idx_carrinho_item_oferta
    ON carrinho_item (oferta_item_id);

CREATE INDEX idx_carrinho_item_fornecedor
    ON carrinho_item (fornecedor_id);

-- ============================================================
-- FIM
-- ============================================================

COMMIT;