spring.config.import=file:.env.test[.properties]

# Local sem PostgreSQL/Docker
spring.flyway.enabled=false

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration