--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fonte_neoenergia; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.fonte_neoenergia AS ENUM (
    'NEOENERGIA_REDE',
    'NEOENERGIA_SUBESTACOES'
);


--
-- Name: motivo_material; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.motivo_material AS ENUM (
    'MATCH_EXATO_ATIVO',
    'CANDIDATO_TECNICO_UNICO',
    'CANDIDATOS_AMBIGUOS',
    'SEM_CANDIDATO_COMPATIVEL'
);


--
-- Name: status_associacao; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_associacao AS ENUM (
    'EXATO',
    'SEMASSOCIACAO'
);


--
-- Name: status_carrinho; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_carrinho AS ENUM (
    'RASCUNHO',
    'CALCULADO',
    'APROVADO',
    'CANCELADO'
);


--
-- Name: status_registro; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_registro AS ENUM (
    'ATIVO',
    'INATIVO'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carrinho; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrinho (
    id integer NOT NULL,
    orcamento_id integer NOT NULL,
    status public.status_carrinho DEFAULT 'RASCUNHO'::public.status_carrinho NOT NULL,
    valor_base numeric(18,2),
    valor_otimizado numeric(18,2),
    economia numeric(18,2),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: carrinho_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carrinho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrinho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrinho_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrinho_item (
    id integer NOT NULL,
    carrinho_id integer NOT NULL,
    item_orcamento_id integer NOT NULL,
    oferta_item_id integer,
    fornecedor_id integer,
    quantidade numeric(18,4),
    preco_unitario numeric(18,4),
    preco_total numeric(18,4),
    selecionado_automaticamente boolean DEFAULT false NOT NULL,
    selecionado_usuario boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: carrinho_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carrinho_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrinho_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    documento character varying(50),
    status public.status_registro DEFAULT 'ATIVO'::public.status_registro NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cotacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cotacao (
    id integer NOT NULL,
    fornecedor_id integer NOT NULL,
    numero_cotacao character varying(100),
    data_cotacao timestamp with time zone,
    validade timestamp with time zone,
    frete numeric(18,2),
    desconto numeric(18,2),
    condicao_pagamento character varying(255),
    prazo_entrega character varying(255),
    valor_total numeric(18,2),
    arquivo_origem text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: cotacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cotacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fornecedor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fornecedor (
    id integer NOT NULL,
    razao_social character varying(255) NOT NULL,
    nome_fantasia character varying(255),
    cnpj character varying(30),
    email character varying(255),
    telefone character varying(50),
    status public.status_registro DEFAULT 'ATIVO'::public.status_registro NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: fornecedor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fornecedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_orcamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_orcamento (
    id integer NOT NULL,
    orcamento_id integer NOT NULL,
    numero_item integer,
    codigo_item character varying(255),
    descricao_original text NOT NULL,
    descricao_normalizada text,
    quantidade numeric(18,4),
    unidade character varying(50),
    preco_unitario numeric(18,4),
    preco_total numeric(18,4),
    material_oficial_id integer,
    status_associacao public.status_associacao DEFAULT 'SEMASSOCIACAO'::public.status_associacao NOT NULL,
    motivo_material public.motivo_material,
    match_automatico boolean DEFAULT false NOT NULL,
    revisao_humana_obrigatoria boolean DEFAULT true NOT NULL,
    observacao text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: item_orcamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_orcamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_orcamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: material_fornecedor_homologado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material_fornecedor_homologado (
    id integer NOT NULL,
    material_neoenergia_id integer NOT NULL,
    fornecedor_id integer NOT NULL,
    referencia_fornecedor character varying(255),
    desenho_fornecedor character varying(255),
    data_homologacao timestamp with time zone,
    data_vencimento_homologacao timestamp with time zone,
    documentacao text,
    modo_fornecimento character varying(255),
    ca character varying(255),
    tipo_gestao_recebimento character varying(255),
    status_homologacao character varying(100),
    observacao text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: material_fornecedor_homologado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.material_fornecedor_homologado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_fornecedor_homologado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: material_neoenergia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material_neoenergia (
    id integer NOT NULL,
    material_oficial_id integer,
    codigo_nordeste character varying(255),
    codigo_elektro character varying(255),
    codigo_brasilia character varying(255),
    descricao text NOT NULL,
    descricao_completa text,
    especificacao_tecnica text,
    familia character varying(255),
    subfamilia character varying(255),
    fonte public.fonte_neoenergia NOT NULL,
    chave_importacao text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: material_neoenergia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.material_neoenergia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_neoenergia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: material_oficial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material_oficial (
    id integer NOT NULL,
    nome character varying(500) NOT NULL,
    nome_normalizado character varying(500) NOT NULL,
    categoria character varying(255),
    especificacao_tecnica text,
    status public.status_registro DEFAULT 'ATIVO'::public.status_registro NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: material_oficial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.material_oficial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_oficial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oferta_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oferta_item (
    id integer NOT NULL,
    cotacao_id integer NOT NULL,
    fornecedor_id integer NOT NULL,
    material_oficial_id integer,
    descricao_fornecedor text NOT NULL,
    quantidade numeric(18,4),
    unidade character varying(50),
    preco_unitario numeric(18,4),
    preco_total numeric(18,4),
    prazo_entrega character varying(255),
    valida boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: oferta_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.oferta_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oferta_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orcamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orcamento (
    id integer NOT NULL,
    numero_orcamento character varying(100),
    cliente_id integer,
    fornecedor_origem_id integer,
    data_orcamento timestamp with time zone,
    subtotal numeric(18,2),
    frete numeric(18,2),
    desconto numeric(18,2),
    tributos numeric(18,2),
    valor_total numeric(18,2),
    status character varying(50),
    arquivo_origem text,
    drive_file_id character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: orcamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orcamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orcamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrinho_item carrinho_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho_item
    ADD CONSTRAINT carrinho_item_pkey PRIMARY KEY (id);


--
-- Name: carrinho carrinho_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho
    ADD CONSTRAINT carrinho_pkey PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: cotacao cotacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotacao
    ADD CONSTRAINT cotacao_pkey PRIMARY KEY (id);


--
-- Name: fornecedor fornecedor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT fornecedor_pkey PRIMARY KEY (id);


--
-- Name: item_orcamento item_orcamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_orcamento
    ADD CONSTRAINT item_orcamento_pkey PRIMARY KEY (id);


--
-- Name: material_fornecedor_homologado material_fornecedor_homologado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_fornecedor_homologado
    ADD CONSTRAINT material_fornecedor_homologado_pkey PRIMARY KEY (id);


--
-- Name: material_neoenergia material_neoenergia_chave_importacao_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_neoenergia
    ADD CONSTRAINT material_neoenergia_chave_importacao_key UNIQUE (chave_importacao);


--
-- Name: material_neoenergia material_neoenergia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_neoenergia
    ADD CONSTRAINT material_neoenergia_pkey PRIMARY KEY (id);


--
-- Name: material_oficial material_oficial_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_oficial
    ADD CONSTRAINT material_oficial_pkey PRIMARY KEY (id);


--
-- Name: oferta_item oferta_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oferta_item
    ADD CONSTRAINT oferta_item_pkey PRIMARY KEY (id);


--
-- Name: orcamento orcamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT orcamento_pkey PRIMARY KEY (id);


--
-- Name: material_fornecedor_homologado uq_mfh_material_fornecedor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_fornecedor_homologado
    ADD CONSTRAINT uq_mfh_material_fornecedor UNIQUE (material_neoenergia_id, fornecedor_id);


--
-- Name: idx_carrinho_item_carrinho; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrinho_item_carrinho ON public.carrinho_item USING btree (carrinho_id);


--
-- Name: idx_carrinho_item_fornecedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrinho_item_fornecedor ON public.carrinho_item USING btree (fornecedor_id);


--
-- Name: idx_carrinho_item_oferta; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrinho_item_oferta ON public.carrinho_item USING btree (oferta_item_id);


--
-- Name: idx_carrinho_item_orcamento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrinho_item_orcamento ON public.carrinho_item USING btree (item_orcamento_id);


--
-- Name: idx_carrinho_orcamento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrinho_orcamento ON public.carrinho USING btree (orcamento_id);


--
-- Name: idx_cliente_nome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cliente_nome ON public.cliente USING btree (nome);


--
-- Name: idx_cotacao_fornecedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cotacao_fornecedor ON public.cotacao USING btree (fornecedor_id);


--
-- Name: idx_cotacao_numero; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cotacao_numero ON public.cotacao USING btree (numero_cotacao);


--
-- Name: idx_fornecedor_cnpj; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fornecedor_cnpj ON public.fornecedor USING btree (cnpj);


--
-- Name: idx_fornecedor_razao_social; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fornecedor_razao_social ON public.fornecedor USING btree (razao_social);


--
-- Name: idx_item_orcamento_codigo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_orcamento_codigo ON public.item_orcamento USING btree (codigo_item);


--
-- Name: idx_item_orcamento_material; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_orcamento_material ON public.item_orcamento USING btree (material_oficial_id);


--
-- Name: idx_item_orcamento_orcamento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_orcamento_orcamento ON public.item_orcamento USING btree (orcamento_id);


--
-- Name: idx_material_neoenergia_codigo_nordeste; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_neoenergia_codigo_nordeste ON public.material_neoenergia USING btree (codigo_nordeste);


--
-- Name: idx_material_neoenergia_fonte; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_neoenergia_fonte ON public.material_neoenergia USING btree (fonte);


--
-- Name: idx_material_neoenergia_material; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_neoenergia_material ON public.material_neoenergia USING btree (material_oficial_id);


--
-- Name: idx_material_oficial_categoria; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_oficial_categoria ON public.material_oficial USING btree (categoria);


--
-- Name: idx_material_oficial_nome_normalizado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_oficial_nome_normalizado ON public.material_oficial USING btree (nome_normalizado);


--
-- Name: idx_mfh_fornecedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfh_fornecedor ON public.material_fornecedor_homologado USING btree (fornecedor_id);


--
-- Name: idx_mfh_material; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfh_material ON public.material_fornecedor_homologado USING btree (material_neoenergia_id);


--
-- Name: idx_oferta_cotacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oferta_cotacao ON public.oferta_item USING btree (cotacao_id);


--
-- Name: idx_oferta_fornecedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oferta_fornecedor ON public.oferta_item USING btree (fornecedor_id);


--
-- Name: idx_oferta_material; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oferta_material ON public.oferta_item USING btree (material_oficial_id);


--
-- Name: idx_oferta_valida; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oferta_valida ON public.oferta_item USING btree (valida);


--
-- Name: idx_orcamento_cliente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orcamento_cliente ON public.orcamento USING btree (cliente_id);


--
-- Name: idx_orcamento_fornecedor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orcamento_fornecedor ON public.orcamento USING btree (fornecedor_origem_id);


--
-- Name: idx_orcamento_numero; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orcamento_numero ON public.orcamento USING btree (numero_orcamento);


--
-- Name: carrinho_item fk_carrinho_item_carrinho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho_item
    ADD CONSTRAINT fk_carrinho_item_carrinho FOREIGN KEY (carrinho_id) REFERENCES public.carrinho(id) ON DELETE CASCADE;


--
-- Name: carrinho_item fk_carrinho_item_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho_item
    ADD CONSTRAINT fk_carrinho_item_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);


--
-- Name: carrinho_item fk_carrinho_item_oferta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho_item
    ADD CONSTRAINT fk_carrinho_item_oferta FOREIGN KEY (oferta_item_id) REFERENCES public.oferta_item(id);


--
-- Name: carrinho_item fk_carrinho_item_orcamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho_item
    ADD CONSTRAINT fk_carrinho_item_orcamento FOREIGN KEY (item_orcamento_id) REFERENCES public.item_orcamento(id);


--
-- Name: carrinho fk_carrinho_orcamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrinho
    ADD CONSTRAINT fk_carrinho_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamento(id);


--
-- Name: cotacao fk_cotacao_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cotacao
    ADD CONSTRAINT fk_cotacao_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);


--
-- Name: item_orcamento fk_item_orcamento_material; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_orcamento
    ADD CONSTRAINT fk_item_orcamento_material FOREIGN KEY (material_oficial_id) REFERENCES public.material_oficial(id);


--
-- Name: item_orcamento fk_item_orcamento_orcamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_orcamento
    ADD CONSTRAINT fk_item_orcamento_orcamento FOREIGN KEY (orcamento_id) REFERENCES public.orcamento(id) ON DELETE CASCADE;


--
-- Name: material_neoenergia fk_material_neoenergia_material; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_neoenergia
    ADD CONSTRAINT fk_material_neoenergia_material FOREIGN KEY (material_oficial_id) REFERENCES public.material_oficial(id);


--
-- Name: material_fornecedor_homologado fk_mfh_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_fornecedor_homologado
    ADD CONSTRAINT fk_mfh_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);


--
-- Name: material_fornecedor_homologado fk_mfh_material; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_fornecedor_homologado
    ADD CONSTRAINT fk_mfh_material FOREIGN KEY (material_neoenergia_id) REFERENCES public.material_neoenergia(id) ON DELETE CASCADE;


--
-- Name: oferta_item fk_oferta_cotacao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oferta_item
    ADD CONSTRAINT fk_oferta_cotacao FOREIGN KEY (cotacao_id) REFERENCES public.cotacao(id) ON DELETE CASCADE;


--
-- Name: oferta_item fk_oferta_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oferta_item
    ADD CONSTRAINT fk_oferta_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(id);


--
-- Name: oferta_item fk_oferta_material; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oferta_item
    ADD CONSTRAINT fk_oferta_material FOREIGN KEY (material_oficial_id) REFERENCES public.material_oficial(id);


--
-- Name: orcamento fk_orcamento_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT fk_orcamento_cliente FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: orcamento fk_orcamento_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT fk_orcamento_fornecedor FOREIGN KEY (fornecedor_origem_id) REFERENCES public.fornecedor(id);


--
-- PostgreSQL database dump complete
--


