services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - private_network
      - public_network

networks:
  private_network:
  public_network: