services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - database_network
      - public_network

networks:
  database_network:
    external: true
    name: database_default

  public_network: