apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  MICROSOFT_CLIENT_ID: "seu-client-id"
  MICROSOFT_CLIENT_SECRET: "seu-client-secret"
  MICROSOFT_SERVICE_CLIENT_ID: "seu-service-client-id"
  MICROSOFT_SERVICE_CLIENT_SECRET: "seu-service-client-secret"
  N8N_API_KEY: "sua-chave-n8n"