name: CI

on:
  push:
    branches:
      - infra-lab
  pull_request:
    branches:
      - infra-lab

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ============================================================
  # TEST
  # ============================================================
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test
        working-directory: system/services/auth-service
        run: ./mvnw verify

  # ============================================================
  # BUILD + SECURITY + PUBLISH
  # ============================================================
  image:
    name: Build, Scan and Publish
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: system/services/auth-service
          file: system/services/auth-service/Dockerfile
          load: true
          push: false
          tags: auth-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: auth-service:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        if: github.event_name == 'push'
        run: |
          docker tag \
            auth-service:${{ github.sha }} \
            ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }}

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }}